image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "27"
  ANDROID_BUILD_TOOLS: "27.0.3"
  ANDROID_SDK_TOOLS: "24.4.1"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
  - unzip android-sdk.zip -d android-sdk-linux
  - mkdir android-sdk-linux/licenses || true
  - printf "24333f8a63b6825ea9c5514f83c2829b004d1fee" > android-sdk-linux/licenses/android-sdk-license
  - android-sdk-linux/tools/bin/sdkmanager --list
  - android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}" > platform_log.txt
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - chmod +x ./gradlew

stages:
  - build
  - test

BuildBinary:
  stage: build
  only:
    - develop
  script:
    - ./gradlew build
  artifacts:
    paths:
    - app/build/outputs/

UnitTests:
  stage: test
  script:
    - ./gradlew test
